exports.commands=
[
	{
		name: 'bullshit',
		func: function(params)
		{
			var max1 = 65;
			var max2 = 89;
			var max3 = 91;
			var max4 = 107 ;

			var index1 = Math.round(Math.random() * max1);	
			var index2 = Math.round(Math.random() * max2);	
			var index3 = Math.round(Math.random() * max3);	
			var index4 = Math.round(Math.random() * max4);	


			var array1 = new Array("Eroforrás-alapú megközelítéssel kell",
			"Egy absztrakciós létra mentén kell",
			"Alapveto fontosságú",
			"Kiemelt projektünk",
			"A menedzsment célja",
			"Teljes összhangban kell",
			"Belso kommunikáció révén kell",
			"Csapatmunkában szükséges",
			"Még ma szükséges",
			"Nem tur halasztást",
			"Fontos lenne", 
			"Szükséges lenne", 
			"Szükséges", 
			"Vállalatunk célja", 
			"Kiemelt fontosságú feladat",
			"Ennek szellemében kell",
			"Formállogikai alapon kellene",
			"Alkotó folyamat keretében kell",
			"Felelosséggel kell",
			"A következot kell tennünk:",
			"Egyetlen megoldásunk van:",
			"Az egyetlen kiút:",
			"Tanácsadóink szerint célunk:",
			"A menedzsment szeretné",
			"Az üzletág szeretné",
			"Most kell",
			"Nincs más hátra, mint",
			"Ne felejtsük el",
			"Ne szalasszuk el",
			"Szeretném",
			"Célom",
			"Az eddigiek szerint kell",
			"A lényeg:",
			"Feladatunk:",
			"Küldetésünk:",
			"A mai legfontosabb prioritás:",
			"Megpróbáljuk",
			"Megpróbálom",
			"Megkíséreljük",
			"Megkísérlem",
			"Próbáljátok meg",
			"Meg kell próbálnunk",
			"Küldetésem",
			"Új koncepció szerint kell",
			"Azonnal szükséges",
			"Egy megoldás van:",
			"Kreatív módon kell",
			"Sürgosen szükséges",
			"Személyes célom",
			"Nincs más dolgunk, mint",
			"Nincs más feladatom, mint",
			"Legfontosabb feladatom",
			"Legfontosabb küldetésem",
			"Elsodleges fontosságú lenne",
			"Elengedhetetlen lenne",
			"Létfontosságú dolog",
			"Elengedhetetlenül fontos lenne",
			"Itt az ido",
			"Nem halaszthatjuk el",
			"Kreatív módon kell",
			"Elemzések segítségével kell",
			"Kreatív módon kéne",
			"Látványosan kell",
			"Minél feltunobben kell",
			"Professzionális módon kell",
			"Megfelelo idozítéssel kell");

			var array2 = new Array("implementálni", 
			"átültetni",
			"aggregálni", 
			"aktívan menedzselni",
			"aktiválni",
			"allokálni", 
			"analizálni", 
			"áramvonalasítani", 
			"arányosítani", 
			"áthangszerelni", 
			"átváltoztatni", 
			"átvariálni", 
			"átvezetni", 
			"bátorítani",
			"betanítani",
			"befolyásolni", 
			"benchmarkolni", 
			"bevetni", 
			"birtokba venni", 
			"bovíteni", 
			"szukíteni", 
			"ellenorizni", 
			"elomozdítani", 
			"életre kelteni",
			"facilitálni", 
			"fejleszteni", 
			"felnevelni", 
			"felruházni", 
			"felszabadítani", 
			"forradalmasítani", 
			"generálni", 
			"hasznosítani", 
			"hatékonyabbá tenni", 
			"innovatívan fejleszteni", 
			"integrálni", 
			"iterálni", 
			"kihangsúlyozni",
			"kiválasztani",
			"leválogatni", 
			"leválasztani", 
			"kihasználni",
			"kiterjeszteni", 
			"kultiválni", 
			"lefoglalni", 
			"lehetové tenni", 
			"márkázni", 
			"maximalizálni", 
			"meghatározni", 
			"megragadni", 
			"megváltoztatni", 
			"menedzselni", 
			"monetizálni", 
			"motiválni",
			"növelni", 
			"nyilvánvalóvá tenni", 
			"optimalizálni", 
			"ösztönözni", 
			"kiépíteni", 
			"rávilágítani",
			"racionálisan végiggondolni",
			"racionalizálni", 
			"ritkítani",
			"suríteni",
			"strategizálni", 
			"struktúrálni", 
			"szakmailag felügyelni", 
			"szétszabdalni", 
			"szimulálni",
			"szindikálni", 
			"szinergizálni", 
			"szinkronba hozni", 
			"sztenderdizálni",
			"szintetizálni", 
			"támogatni",
			"targetálni", 
			"termékesíteni", 
			"testreszabni",
			"toborozni",
			"tipizálni",
			"tiszta lappal kezdeni", 
			"transzformálni", 
			"túlteljesíteni", 
			"új kontextusba helyezni", 
			"újra feltalálni", 
			"újra meghatározni", 
			"újradefiniálni", 
			"újrapozícionálni", 
			"újratermelni", 
			"vizionálni", 
			"vizualizálni");

			var array3 = new Array("a közösségi normáknak megfelelo", 
			"a decentralizált", 
			"a dinamikusan növekvo", 
			"a dinamikusan növekvo", 
			"a divergens",
			"a fontos",
			"a felvállalható", 
			"a forradalmian új", 
			"a funkció-specifikus", 
			"a globális preferenciák szerinti", 
			"a hatásos", 
			"a hatékony", 
			"a hibátlan", 
			"a holisztikus", 
			"a kihívást jelento", 
			"a konvergens",
			"a konzisztens", 
			"a korrigálható",
			"a korreláló", 
			"a költséghatékony", 
			"a közszolgáltatási", 
			"a kultúraidegen",
			"a kritikus", 
			"a kvázi-projekt-szeru",
			"a marketing-szemléletu", 
			"a megfeleloen elokészített",
			"a meghatározandó",
			"a megtérülo",
			"a metakommunkiációs", 
			"a one-stop-shop-szeru",
			"az összehangolt",
			"a piacvezeto", 
			"a proaktív", 
			"a prudens",
			"a reakcióképes",
			"a robosztus", 
			"a racionális",
			"a rendszeres", 
			"a rugalmas", 
			"a sajátos", 
			"a stagnáló", 
			"a stratégiai céloknak megfelelo", 
			"a stratégiáknak megfelelo", 
			"a súrlódásmentes", 
			"a szárnyaló", 
			"a széles körben használt", 
			"a személyre szabott", 
			"a szinergizált", 
			"a tudatos", 
			"a vállalati szintu", 
			"a vállalati szintu", 
			"a vállalatspecifikus", 
			"a vállalható", 
			"a valós ideju", 
			"a vertikális", 
			"a világszínvonalú", 
			"a virtuális", 
			"a vizionált", 
			"a vonzáskörzeten belüli", 
			"a XXI. századi színvonalú", 
			"az autonóm",
			"a heteronóm",
			"az apatikus",
			"a közömbös",
			"a személyközi",
			"a szukös",
			"a rutinos",
			"az atipikus", 
			"az átlátható", 
			"az attraktív", 
			"az egységsugarú", 
			"az együttmuködo", 
			"az elosztott", 
			"az elovárosi",
			"az elonyös", 
			"az értéklánc menti", 
			"az értéknövelt", 
			"az európai színvonalú", 
			"az európai uniós", 
			"az extenzív", 
			"az idozített",
			"az igazgató úr által is említett", 
			"az innovatív", 
			"az integrált", 
			"az interaktív", 
			"az intuitív", 
			"az irányvonalnak megfelelo", 
			"az ügyfélbarát", 
			"az ügyfélközpontú", 
			"az ügyféloldali", 
			"az ütemes", 
			"a távolsági");

			var array4 = new Array("szinergiákat", 
			"adatbázist", 
			"ágazatközi munkamegosztást", 
			"akció-rádiuszt", 
			"akcióterveket",
			"belso hatékonyságot",
			"beruházási megtérülést", 
			"beszállító-menedzsmentet", 
			"csatlakozási pontokat", 
			"csapatot",
			"csatornákat", 
			"derogációt", 
			"desztinációszenzitív portfoliót", 
			"együttmuködéseket",
			"egységköltséget",
			"egység-díjtételt", 
			"ellátási láncokat", 
			"emberi eroforrást", 
			"eredményjavító hatást", 
			"eroforrás-menedzsmentet", 
			"eroforrásokat", 
			"értékláncot",
			"értékesítési rendszert", 
			"fejlesztéseket", 
			"feladatmegosztást", 
			"flotta-menedzsmentet", 
			"fogyasztói bázist",
			"frontvonalat",
			"front-office-t",
			"front-office on-stage vonalat", 
			"front-office backstage vonalat", 
			"hálózatokat", 
			"háttérszolgáltatásokat", 
			"hatalmi centrumot",
			"imázs-alakítást", 
			"infrastruktúrákat", 
			"intermodalitást", 
			"interoperabilitást", 
			"irányelveket",
			"irányítási filozófiát", 
			"jogharmonizációt", 
			"kapacitás-kihasználtságot", 
			"kapcsolatokat", 
			"kezdeményezéseket", 
			"koncepciót", 
			"kontextust",
			"kontrollingot", 
			"konvergenciákat",
			"költségérzékeny szegmenst",
			"környezet-elemzést",
			"kritériumokat",
			"látványtechnológiát",
			"leválasztási stratégiát",
			"marketing-kutatást", 
			"marketing-miómát",
			"marketing-szemléletet",
			"megoldásokat", 
			"méretgazdaságosságot",
			"mérföldköveket", 
			"metodológiákat", 
			"minoségi szolgáltatásokat", 
			"minposégi indikátorokat",
			"minoség-monitoringot",
			"munkacsoportot",
			"muködési költségeket",
			"optimalizálási koncepciót", 
			"outsourcingot", 
			"paradigmákat", 
			"piaci megjelenést", 
			"piaci potenciált", 
			"piaci pozíciót", 
			"piaci réseket",
			"piaci trendeket",
			"piacokat", 
			"pilot projektet", 
			"platformokat", 
			"portálokat", 
			"projekteket", 
			"reklámanyagot", 
			"rendszereket", 
			"rendszertervezési technológiát",
			"sémákat", 
			"stratégiai célokat", 
			"szabályozásokat", 
			"szegmentumokat", 
			"személyszállítást",
			"szervezeti kultúrát",
			"szolgáltatási folyamatrendszert",
			"szolgáltatás-felügyeletet", 
			"szolgáltatást", 
			"sztenderdizációt",
			"támogató tevékenységet",
			"termékpalettát",
			"termékportfolió-átalakítást",
			"technológiákat",
			"tevékenység-menedzsmentet",
			"tudásközpontot",
			"tranzakciós költséget", 
			"újraelosztó-rendszert", 
			"ügyfeleket",
			"ügyfélreferenst",
			"ügyfél-kiszolgálást", 
			"ügyfélorientált trendeket",
			"üzletmenetet", 
			"vállalati imázst",
			"VIP-ügyfeleket",
			"versenyhelyzetet",
			"versenyelony-forrást"); 
			index1 = Math.round(Math.random() * max1);
			index2 = Math.round(Math.random() * max2);	
			index3 = Math.round(Math.random() * max3);	
			index4 = Math.round(Math.random() * max4);	
			this.say(array1[index1] + " " + array2[index2] + " " + array3[index3] + " " + array4[index4] +".");
		}
	}
]